import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import { NavBar } from "@/components/layouts/NavBar";
import "./globals.css";
import PaRappaDaWrapper from "@/components/layouts/PaRappaDaWrapper";
import Footer from "@/components/layouts/Footer";

const monaSans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${monaSans.variable} antialiased min-h-screen overflow-hidden`}
      >
        <PaRappaDaWrapper>
          <NavBar />
          {children}
          <Footer />
        </PaRappaDaWrapper>
      </body>
    </html>
  );
}
